#!/usr/bin/env bash

set -TCEeuo pipefail

bump_type=${1:-patch}

# Get the next version
export GIT_CLIFF__BUMP__INITIAL_TAG=v0.1.0 # by default it's 0.1.0
next_version=$(git cliff --unreleased --bump "$bump_type" --context --tag-pattern "v[0-9]+\\.[0-9]+\\.[0-9]+" | jq -r '.[0].version' | tr -d "v")

# Generate the doc
bashlib-docgen \
  --output-dir "docs/released" \
  --doc-version "$next_version"

# Generate the main page
bashlib-mangen \
  --output-dir "out/man1"

# Check the generated doc
if ! git-prepare; then
  echo "Error found while preparing the release commit"
fi

# Release
JRELEASER_PROJECT_VERSION="$next_version" jreleaser release

echo "Version release of $next_version done"
