version: '3'

tasks:
  # Start the dev server
  start:
    cmds:
      - |
        docgen -w&
        npx docusaurus start
  # Deploy (Normally done with release script)
  # task deploy -- v0.1.0
  deploy:
    cmds:
      - |
        docgen "{{.CLI_ARGS}}"
        npx docusaurus deploy
  kill:
    cmds:
      - |
        kill -9 $(lsof -t -i:3000)
